language: ruby
sudo: required
dist: trusty
branches:
  only:
    - develop
    - master
    - /^release.*$/
    - add_scrip_for_cron
os:
  - linux
services:
  - docker
addons:
  apt:
    packages:
      - git
      - build-essential
  ssh_known_hosts: 52.76.173.135
before_install:
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - chmod +x scripts/travis/build-docker.sh scripts/travis/deploy-image.sh
script:
  - echo "TRAVIS_EVENT_TYPE"
  - echo "$TRAVIS_EVENT_TYPE"
  - echo "TRAVIS_BUILD_DIR"
  - echo $TRAVIS_BUILD_DIR
  if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then $TRAVIS_BUILD_DIR/scripts/upload_workspace_to_s3.sh; exit 0; fi;
  - ./scripts/travis/build-docker.sh
  - ./scripts/travis/deploy-image.sh
notifications:
  email:
    on_success: change
    on_failure: always
